### Some data clean up that's necessary for our project

In [214]:
import pandas as pd
import numpy as np

In [215]:
spotify = pd.read_csv('/Users/michellehewson/Desktop/Harvard/CS171/final_project/cs171_finalproject/data/spotify_top_charts_22.csv')  
tiktok = pd.read_csv('/Users/michellehewson/Desktop/Harvard/CS171/final_project/cs171_finalproject/data/TikTok_songs_2022 2.csv')

In [216]:
# Checking out our data
spotify.head()

,uri,artist_names,track_name,peak_rank,weeks_on_chart,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,tempo,time_signature,duration_ms
0,spotify:track:02MWAaffLxlfxAUY7c5dvx,Glass Animals,Heat Waves,1,65,0.761,0.525,11,-6.900,1,0.0944,0.4400,0.000007,0.0921,80.870,4,238805
1,spotify:track:5PjdY0CKGZdEuoNab3yDmX,"The Kid LAROI, Justin Bieber",STAY (with Justin Bieber),1,37,0.591,0.764,1,-5.484,1,0.0483,0.0383,0.000000,0.1030,169.928,4,141806
2,spotify:track:3IAfUEeaXRX9s9UdKOJrFI,Anitta,Envolver,3,3,0.812,0.736,4,-5.421,0,0.0833,0.1520,0.002540,0.0914,91.993,4,193806
3,spotify:track:1HhNoOuqm1a5MXYEgAFl8o,"Imagine Dragons, JID, Arcane, League of Legends",Enemy (with JID) - from the series Arcane Leag...,3,21,0.728,0.783,11,-4.424,0,0.2660,0.2370,0.000000,0.4340,77.011,4,173381
4,spotify:track:4fouWK6XVHhzl78KzQ1UjL,GAYLE,abcdefu,1,19,0.695,0.540,4,-5.692,1,0.0493,0.2990,0.000000,0.3670,121.932,4,168602

In [217]:
# Need to clean up the names of tracks (the syntax between both of the datasets is not the same)
# TikTok dataset has a lot of "SONG (feat. artist2, artist3)"
# Spotify dataset has "SONG" and then the artist names in the artist_names column
# For simplicity's sake, we'll just count the first artist listed as the owner of the song and ignore the features

spotify['old_track_name'] = spotify['track_name']
spotify['track_name'] = spotify['track_name'].str.split('(', n=1).str[0]
spotify['track_name'] = spotify['track_name'].str.split('-', n=1).str[0]

tiktok['old_track_name'] = tiktok['track_name']
tiktok['track_name'] = tiktok['track_name'].str.split('(', n=1).str[0]
tiktok['track_name'] = tiktok['track_name'].str.split('-', n=1).str[0]

In [218]:
spotify['old_artist_names'] = spotify['artist_names']
spotify['artist_names'] = spotify['artist_names'].str.split(',', n=1).str[0]
spotify = spotify.rename(columns={'artist_names': 'artist_name'})
spotify.head()

,uri,artist_name,track_name,peak_rank,weeks_on_chart,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,tempo,time_signature,duration_ms,old_track_name,old_artist_names
0,spotify:track:02MWAaffLxlfxAUY7c5dvx,Glass Animals,Heat Waves,1,65,0.761,0.525,11,-6.900,1,0.0944,0.4400,0.000007,0.0921,80.870,4,238805,Heat Waves,Glass Animals
1,spotify:track:5PjdY0CKGZdEuoNab3yDmX,The Kid LAROI,STAY,1,37,0.591,0.764,1,-5.484,1,0.0483,0.0383,0.000000,0.1030,169.928,4,141806,STAY (with Justin Bieber),"The Kid LAROI, Justin Bieber"
2,spotify:track:3IAfUEeaXRX9s9UdKOJrFI,Anitta,Envolver,3,3,0.812,0.736,4,-5.421,0,0.0833,0.1520,0.002540,0.0914,91.993,4,193806,Envolver,Anitta
3,spotify:track:1HhNoOuqm1a5MXYEgAFl8o,Imagine Dragons,Enemy,3,21,0.728,0.783,11,-4.424,0,0.2660,0.2370,0.000000,0.4340,77.011,4,173381,Enemy (with JID) - from the series Arcane Leag...,"Imagine Dragons, JID, Arcane, League of Legends"
4,spotify:track:4fouWK6XVHhzl78KzQ1UjL,GAYLE,abcdefu,1,19,0.695,0.540,4,-5.692,1,0.0493,0.2990,0.000000,0.3670,121.932,4,168602,abcdefu,GAYLE

In [219]:
# all of the songs that appear in both datasets (so they're a top song on tiktok AND spotify)
merged_df = pd.merge(tiktok, spotify, on='track_name', how='inner')

In [220]:
# make some new CSVs
#spotify.to_csv('spotify_clean.csv', index=False)
#tiktok.to_csv('tiktok_clean.csv', index=False)
#merged_df.to_csv('tiktok_spotify_merged.csv', index=False)

In [221]:
# Counting how many songs an artist has (they're the first one listed) in the top spotify charts
spotify_artist_counts = spotify['artist_name'].value_counts().reset_index()
spotify_artist_counts.columns = ['artist', 'count']

spotify_artist_counts = pd.DataFrame(spotify_artist_counts)
spotify_artist_counts.head()

           artist  count
0       Bad Bunny     29
1      The Weeknd     27
2  Kendrick Lamar     21
3    Harry Styles     18
4           Drake     18

In [222]:
tiktok_artist_counts = tiktok['artist_name'].value_counts().reset_index()
tiktok_artist_counts.columns = ['artist', 'count']
tiktok_artist_counts.head()

      artist  count
0   Doja Cat      8
1     Coopex      6
2  Dame Dame      5
3  Lil Nas X      4
4      Farux      4

In [223]:
#spotify_artist_counts.to_csv('spotify_artist_counts.csv', index=False)
#tiktok_artist_counts.to_csv('tiktok_artist_counts.csv', index=False)

In [224]:
# creating specific dataframe for key information in the tiktok and spotify datasets

In [225]:
num_tiktok_songs = len(tiktok)
num_spotify_songs = len(spotify)

In [226]:
tiktok_keys = tiktok['key'].value_counts()
tiktok_keys = pd.DataFrame(tiktok_keys).reset_index()
tiktok_keys['percentage'] = round((tiktok_keys['count'] / num_tiktok_songs),3) * 100

tiktok_keys

    key  count  percentage
0    11     33        12.5
1     1     30        11.4
2     6     27        10.3
3     8     27        10.3
4     0     25         9.5
5    10     23         8.7
6     4     23         8.7
7     9     19         7.2
8     5     18         6.8
9     7     18         6.8
10    2     12         4.6
11    3      8         3.0

In [227]:
spotify_keys = spotify['key'].value_counts()
spotify_keys = pd.DataFrame(spotify_keys).reset_index()
spotify_keys['percentage'] = round((spotify_keys['count'] / num_spotify_songs),3) * 100

spotify_keys

    key  count  percentage
0     1    104        16.1
1     8     65        10.1
2     0     63         9.8
3     2     56         8.7
4     5     55         8.5
5    11     54         8.4
6     7     52         8.0
7     4     45         7.0
8    10     45         7.0
9     9     42         6.5
10    6     38         5.9
11    3     27         4.2

In [228]:
# make some new CSVs
#spotify_keys.to_csv('spotify_keys.csv', index=False)
#tiktok_keys.to_csv('tiktok_keys.csv', index=False)

In [229]:
tiktok.sort_values(by=['track_pop'], ascending=False)

,track_name,artist_name,artist_pop,album,track_pop,danceability,energy,loudness,mode,key,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,duration_ms,old_track_name
5,Glimpse of Us,Joji,85,Glimpse of Us,97,0.440,0.317,-9.258,1,8,0.0531,0.891000,0.000005,0.1410,0.268,169.914,3,233456,Glimpse of Us
1,As It Was,Harry Styles,91,As It Was,96,0.520,0.731,-5.338,0,6,0.0557,0.342000,0.001010,0.3110,0.662,173.930,4,167303,As It Was
0,Running Up That Hill,Kate Bush,81,Hounds Of Love,95,0.629,0.547,-13.123,0,10,0.0550,0.720000,0.003140,0.0604,0.197,108.375,4,298933,Running Up That Hill (A Deal With God)
52,Late Night Talking,Harry Styles,91,Harry's House,93,0.714,0.728,-4.595,1,10,0.0468,0.298000,0.000000,0.1060,0.901,114.996,4,177955,Late Night Talking
260,Jimmy Cooks,Drake,95,"Honestly, Nevermind",92,0.529,0.673,-4.711,1,0,0.1750,0.000307,0.000002,0.0930,0.366,165.921,4,218365,Jimmy Cooks (feat. 21 Savage)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,She Wolf,YES YES,54,She Wolf (Falling to Pieces),0,0.592,0.719,-5.044,1,2,0.0452,0.008580,0.000000,0.6350,0.169,125.030,4,171028,She Wolf (Falling to Pieces)
75,Looking for Love,Asketa & Natan Chaim,42,Looking for Love,0,0.748,0.894,-4.677,1,7,0.0998,0.311000,0.000029,0.2390,0.503,120.004,4,148000,Looking for Love
68,Lost,Frank Ocean,82,channel ORANGE,0,0.912,0.594,-4.894,0,10,0.2260,0.031900,0.001220,0.1230,0.514,123.070,4,234093,Lost
184,Backyard Boy,Claire Rosinkranz,63,BeVerly Hills BoYfRiEnd,0,0.819,0.642,-7.037,1,5,0.1890,0.336000,0.000000,0.0735,0.452,138.026,4,129241,Backyard Boy
131,What If,HOURS,35,What If,0,0.609,0.777,-5.879,1,6,0.0353,0.001620,0.000001,0.0730,0.349,126.001,4,154286,What If

In [230]:
spotify.sort_values(by=['peak_rank'], ascending=True).head(35)
#spotify.head()

,uri,artist_name,track_name,peak_rank,weeks_on_chart,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,tempo,time_signature,duration_ms,old_track_name,old_artist_names
0,spotify:track:02MWAaffLxlfxAUY7c5dvx,Glass Animals,Heat Waves,1,65,0.761,0.525,11,-6.900,1,0.0944,0.440000,0.000007,0.0921,80.870,4,238805,Heat Waves,Glass Animals
557,spotify:track:7KXjTSCq5nL1LoYtL7XAwS,Kendrick Lamar,HUMBLE.,1,96,0.908,0.621,1,-6.638,0,0.1020,0.000282,0.000054,0.0958,150.011,4,177000,HUMBLE.,Kendrick Lamar
255,spotify:track:7MXVkk9YMctZqd1Srtv4MB,The Weeknd,Starboy,1,97,0.679,0.587,7,-7.015,1,0.2760,0.141000,0.000006,0.1370,186.003,4,230453,Starboy,"The Weeknd, Daft Punk"
246,spotify:track:09mEdoA6zrmBPgTEN5qXmN,The Weeknd,Call Out My Name,1,42,0.461,0.593,1,-4.954,1,0.0356,0.170000,0.000000,0.3070,134.170,3,228373,Call Out My Name,The Weeknd
207,spotify:track:6xGruZOHLs39ZbVccQTuPZ,Joji,Glimpse of Us,1,9,0.440,0.317,8,-9.258,1,0.0531,0.891000,0.000005,0.1410,169.914,3,233456,Glimpse of Us,Joji
54,spotify:track:5wANPM4fQCJwkGd4rN57mH,Olivia Rodrigo,drivers license,1,63,0.561,0.431,10,-8.810,1,0.0578,0.768000,0.000014,0.1060,143.875,4,242013,drivers license,Olivia Rodrigo
204,spotify:track:75FEaRjZTKLhTrFGsfMUXR,Kate Bush,Running Up That Hill,1,11,0.629,0.547,10,-13.123,0,0.0550,0.720000,0.003140,0.0604,108.375,4,298933,Running Up That Hill (A Deal With God),Kate Bush
58,spotify:track:4MzXwWMhyBbmu6hOcLVD49,Bad Bunny,DÁKITI,1,73,0.731,0.573,4,-10.059,0,0.0544,0.401000,0.000052,0.1130,109.928,4,205090,DÁKITI,"Bad Bunny, Jhay Cortez"
201,spotify:track:4Dvkj6JhhA12EX05fT7y2e,Harry Styles,As It Was,1,19,0.520,0.731,6,-5.338,0,0.0557,0.342000,0.001010,0.3110,173.930,4,167303,As It Was,Harry Styles
26,spotify:track:0VjIjW4GlUZAMYd2vXMi3b,The Weeknd,Blinding Lights,1,121,0.514,0.730,1,-5.934,1,0.0598,0.001460,0.000095,0.0897,171.005,4,200040,Blinding Lights,The Weeknd
200,spotify:track:2tTmW7RDtMQtBk7m2rYeSw,Bizarrap,"Quevedo: Bzrp Music Sessions, Vol. 52",1,5,0.621,0.782,2,-5.548,1,0.0440,0.012500,0.033000,0.2300,128.033,4,198938,"Quevedo: Bzrp Music Sessions, Vol. 52","Bizarrap, Quevedo"
68,spotify:track:3Wrjm47oTz2sjIgck11l5e,Måneskin,Beggin',1,42,0.714,0.800,11,-4.808,0,0.0504,0.127000,0.000000,0.3590,134.002,4,211560,Beggin',Måneskin
182,spotify:track:35mvY5S1H3J2QZyna3TFe0,Ariana Grande,positions,1,74,0.737,0.802,0,-4.771,1,0.0878,0.468000,0.000000,0.0931,144.015,4,172325,positions,Ariana Grande
166,spotify:track:2N8m6CYs74qQO4mjVcXO30,Tones And I,Dance Monkey,1,140,0.824,0.587,6,-6.401,0,0.0937,0.690000,0.000105,0.1490,98.029,4,209438,Dance Monkey,Tones And I
158,spotify:track:21jGcNKet2qwijlDFuPiPb,Post Malone,Circles,1,134,0.695,0.762,0,-3.497,1,0.0395,0.192000,0.002440,0.0863,120.042,4,215280,Circles,Post Malone
157,spotify:track:5enxwA8aAbwZbf5qCHORXi,Taylor Swift,All Too Well,1,19,0.631,0.518,0,-8.771,1,0.0303,0.274000,0.000000,0.0880,93.023,4,613027,All Too Well (10 Minute Version) (Taylor's Ver...,Taylor Swift
154,spotify:track:4jPy3l0RUwlUI9T5XHBW2m,24kGoldn,Mood,1,85,0.701,0.716,7,-3.671,0,0.0361,0.174000,0.000000,0.3240,91.007,4,140533,Mood (feat. iann dior),"24kGoldn, iann dior"
139,spotify:track:7qiZfU4dY1lWllzX7mPBI3,Ed Sheeran,Shape of You,1,269,0.825,0.652,1,-3.183,0,0.0802,0.581000,0.000000,0.0931,95.977,4,233713,Shape of You,Ed Sheeran
87,spotify:track:4iJyoBOLtHqaGxP12qzhQI,Justin Bieber,Peaches,1,53,0.677,0.696,0,-6.181,1,0.1190,0.321000,0.000000,0.4200,90.030,4,198082,Peaches (feat. Daniel Caesar & Giveon),"Justin Bieber, Daniel Caesar, Giveon"
194,spotify:track:6v3KW9xbzN5yKLt9YKDYA2,Shawn Mendes,Señorita,1,138,0.759,0.548,9,-6.049,0,0.0290,0.039200,0.000000,0.0828,116.967,4,190800,Señorita,"Shawn Mendes, Camila Cabello"
23,spotify:track:4ZtFanR9U6ndgddUvNcjcG,Olivia Rodrigo,good 4 u,1,45,0.563,0.664,9,-5.044,1,0.1540,0.335000,0.000000,0.0849,166.928,4,178147,good 4 u,Olivia Rodrigo
46,spotify:track:1SC5rEoYDGUK4NfG82494W,Lil Nas X,MONTERO,1,52,0.593,0.503,8,-6.725,0,0.2200,0.293000,0.000000,0.4050,178.781,4,137704,MONTERO (Call Me By Your Name),Lil Nas X
93,spotify:track:0RiRZpuVRbi7oqRdSMwhQY,Post Malone,Sunflower,1,179,0.755,0.522,2,-4.368,1,0.0575,0.533000,0.000000,0.0685,89.960,4,157560,Sunflower - Spider-Man: Into the Spider-Verse,"Post Malone, Swae Lee"
1,spotify:track:5PjdY0CKGZdEuoNab3yDmX,The Kid LAROI,STAY,1,37,0.591,0.764,1,-5.484,1,0.0483,0.038300,0.000000,0.1030,169.928,4,141806,STAY (with Justin Bieber),"The Kid LAROI, Justin Bieber"
11,spotify:track:46IZ0fSY2mpAiktS3KOqds,Adele,Easy On Me,1,23,0.604,0.366,5,-7.519,1,0.0282,0.578000,0.000000,0.1330,141.981,4,224695,Easy On Me,Adele
4,spotify:track:4fouWK6XVHhzl78KzQ1UjL,GAYLE,abcdefu,1,19,0.695,0.540,4,-5.692,1,0.0493,0.299000,0.000000,0.3670,121.932,4,168602,abcdefu,GAYLE
223,spotify:track:1qEmFfgcLObUfQm0j1W2CK,Harry Styles,Late Night Talking,2,12,0.714,0.728,10,-4.595,1,0.0468,0.298000,0.000000,0.1060,114.996,4,177955,Late Night Talking,Harry Styles
53,spotify:track:5QO79kh1waicV47BqGRL3g,The Weeknd,Save Your Tears,2,68,0.680,0.826,0,-5.487,1,0.0309,0.021200,0.000012,0.5430,118.051,4,215627,Save Your Tears,The Weeknd
202,spotify:track:6Sq7ltF9Qa7SNFBsV5Cogx,Bad Bunny,Me Porto Bonito,2,14,0.911,0.712,1,-5.105,0,0.0817,0.090100,0.000027,0.0933,92.005,4,178567,Me Porto Bonito,"Bad Bunny, Chencho Corleone"
231,spotify:track:7ef4DlsgrMEH11cDZd32M6,Calvin Harris,One Kiss,2,83,0.791,0.862,9,-3.240,0,0.1100,0.037000,0.000022,0.0814,123.994,4,214847,One Kiss (with Dua Lipa),"Calvin Harris, Dua Lipa"
235,spotify:track:0wHFktze2PHC5jDt3B17DC,Jack Harlow,First Class,2,18,0.902,0.582,5,-5.902,0,0.1090,0.111000,0.000003,0.1110,107.005,4,173948,First Class,Jack Harlow
189,spotify:track:6RUKPb4LETWmmr3iAEQktW,The Chainsmokers,Something Just Like This,2,172,0.617,0.635,11,-6.769,0,0.0317,0.049800,0.000014,0.1640,103.019,4,247160,Something Just Like This,"The Chainsmokers, Coldplay"
7,spotify:track:5Z9KJZvQzH6PFmb8SNkxuk,Lil Nas X,INDUSTRY BABY,2,35,0.741,0.691,10,-7.395,0,0.0672,0.022100,0.000000,0.0476,150.087,4,212353,INDUSTRY BABY (feat. Jack Harlow),"Lil Nas X, Jack Harlow"
50,spotify:track:1mWdTewIgB3gtBM3TOSFhB,BTS,Butter,2,44,0.759,0.459,8,-5.187,1,0.0948,0.003230,0.000000,0.0906,109.997,4,164442,Butter,BTS
388,spotify:track:4cktbXiXOapiLBMprHFErI,Maroon 5,Memories,2,116,0.775,0.327,11,-7.241,1,0.0557,0.841000,0.000000,0.0821,91.050,4,189486,Memories,Maroon 5

In [231]:
# clean data and combine for bubble chart

In [232]:
len(spotify)

646

In [233]:
spotify_songs = len(spotify)
tiktok_songs = len(tiktok)

spotify_artist_counts = spotify['artist_name'].value_counts().reset_index()
spotify_artist_counts.columns = ['artist_name', 'count']
spotify_artist_counts['data_src'] = 'spotify'
spotify_artist_counts['sizeratio'] = spotify_artist_counts['count'] / spotify_songs

tiktok_artist_counts = tiktok['artist_name'].value_counts().reset_index()
tiktok_artist_counts.columns = ['artist_name', 'count']
tiktok_artist_counts['data_src'] = 'tiktok'
tiktok_artist_counts['sizeratio'] = tiktok_artist_counts['count'] / tiktok_songs

In [234]:
len(tiktok_artist_counts), len(spotify_artist_counts)

(199, 319)

In [235]:
common_artists = set(spotify_artist_counts['artist_name']).intersection(set(tiktok_artist_counts['artist_name']))

common_artist_count = []
for artist in common_artists:
    spotify_count = spotify_artist_counts.loc[spotify_artist_counts['artist_name'] == artist, 'count'].iloc[0]
    tiktok_count = tiktok_artist_counts.loc[tiktok_artist_counts['artist_name'] == artist, 'count'].iloc[0]
    sizeratio = spotify_artist_counts.loc[spotify_artist_counts['artist_name'] == artist, 'sizeratio'].iloc[0]
    common_artist_count.append({'artist_name': artist, 'spotify_count': spotify_count, 'tiktok_count': tiktok_count, 'sizeratio':sizeratio, 'data_src':'both'})

common_artist_count = pd.DataFrame(common_artist_count)

spotify_artist_counts = spotify_artist_counts[~spotify_artist_counts['artist_name'].isin(common_artists)]
tiktok_artist_counts = tiktok_artist_counts[~tiktok_artist_counts['artist_name'].isin(common_artists)]

In [236]:
len(common_artist_count), len(tiktok_artist_counts), len(spotify_artist_counts)

(69, 130, 250)

In [237]:
common_artist_count.head()

  artist_name  spotify_count  tiktok_count  sizeratio data_src
0       Lizzo              2             1   0.003096     both
1  Elton John              1             1   0.001548     both
2   Rosa Linn              1             1   0.001548     both
3     Becky G              1             1   0.001548     both
4   Kate Bush              1             1   0.001548     both

In [238]:
tiktok_artist_counts.head()

      artist_name  count data_src  sizeratio
1          Coopex      6   tiktok   0.022814
2       Dame Dame      5   tiktok   0.019011
4           Farux      4   tiktok   0.015209
5  Alex Alexander      4   tiktok   0.015209
6         YES YES      4   tiktok   0.015209

In [239]:
combined_artists = pd.merge(spotify_artist_counts, tiktok_artist_counts, on='artist_name', how='outer', suffixes=('_spotify', '_tiktok'))
combined_artists = pd.merge(combined_artists, common_artist_count, on='artist_name', how='outer', suffixes=('', '_other'))

combined_artists['spotify_count'].fillna(0, inplace=True)
combined_artists['tiktok_count'].fillna(0, inplace=True)

In [240]:
combined_artists.head(-5)

,artist_name,count_spotify,data_src_spotify,sizeratio_spotify,count_tiktok,data_src_tiktok,sizeratio_tiktok,spotify_count,tiktok_count,sizeratio,data_src
0,Bad Bunny,29.0,spotify,0.044892,NaN,NaN,NaN,0.0,0.0,NaN,NaN
1,Kendrick Lamar,21.0,spotify,0.032508,NaN,NaN,NaN,0.0,0.0,NaN,NaN
2,Beyoncé,16.0,spotify,0.024768,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,Taylor Swift,8.0,spotify,0.012384,NaN,NaN,NaN,0.0,0.0,NaN,NaN
4,BTS,8.0,spotify,0.012384,NaN,NaN,NaN,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
439,SALES,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,0.001548,both
440,CKay,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,0.003096,both
441,Rauw Alejandro,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,0.006192,both
442,Imagine Dragons,NaN,NaN,NaN,NaN,NaN,NaN,6.0,1.0,0.009288,both
443,Drake,NaN,NaN,NaN,NaN,NaN,NaN,18.0,2.0,0.027864,both

In [241]:
sizeratio_columns = ['sizeratio_spotify', 'sizeratio_tiktok', 'sizeratio']

for column in sizeratio_columns:
    combined_artists[column].fillna(0, inplace=True)

combined_artists['sizeratio'] = combined_artists[sizeratio_columns].apply(lambda row: next((cell for cell in row if cell != 0), 0), axis=1)

combined_artists.drop(columns=['sizeratio_spotify', 'sizeratio_tiktok'], inplace=True)

In [242]:
data_src_columns = ['data_src_spotify', 'data_src_tiktok', 'data_src']

for column in data_src_columns:
    combined_artists[column].fillna('', inplace=True)

combined_artists['data_src'] = combined_artists[data_src_columns].apply(lambda row: next((cell for cell in row if cell != ''), ''), axis=1)

combined_artists.drop(columns=['data_src_spotify', 'data_src_tiktok'], inplace=True)

In [245]:
combined_artists.head(-5)

,artist_name,count_spotify,count_tiktok,spotify_count,tiktok_count,sizeratio,data_src
0,Bad Bunny,29.0,NaN,0.0,0.0,0.044892,spotify
1,Kendrick Lamar,21.0,NaN,0.0,0.0,0.032508,spotify
2,Beyoncé,16.0,NaN,0.0,0.0,0.024768,spotify
3,Taylor Swift,8.0,NaN,0.0,0.0,0.012384,spotify
4,BTS,8.0,NaN,0.0,0.0,0.012384,spotify
...,...,...,...,...,...,...,...
439,SALES,NaN,NaN,1.0,2.0,0.001548,both
440,CKay,NaN,NaN,2.0,1.0,0.003096,both
441,Rauw Alejandro,NaN,NaN,4.0,1.0,0.006192,both
442,Imagine Dragons,NaN,NaN,6.0,1.0,0.009288,both
443,Drake,NaN,NaN,18.0,2.0,0.027864,both

In [246]:
combined_artists.to_csv('combined_artists.csv', index=False)